version: "3.8"

services:
    api:
        container_name: puncty_api
        build: .
        restart: always
        volumes:
            - ./data:/app/data
        labels:
            caddy: api.puncty.de
            caddy.reverse_proxy: "{{upstreams http 8002}}"
networks:
    default:
        external:
            name: aproxymate_caddy
