name: ci

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install required packages
        run: |
          pip install -r requirements.txt
          pip install -r dev_requirements.txt
      - name: Run tests
        run: pytest

  build-image:
    name: Build and push docker image
    if: github.ref_name == 'main'
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: tch1b0/puncty-api:latest
